### ISSUE TITLE
Add Star Formation SWG Co-chairs and Steering Committee members

### ISSUE THREAD

**Issue by rpaladini0406** [HWO-GOMAP-Working-Groups/Evolution-Elements#1]
Following request by Abdallah Elsayed (7/11/2024), I would like to add the names of the co-chairs of the SF WSG and those 
of the Steering Committee

**Comment by rpaladini0406** [comment]
The names of the co-chairs are: 
Roberta Paladini (Caltech-IPAC)
Samir Salim (Indiana University)

Steering Committee members: 

Mederic Boquien (Universite' Cote d'Azur)
Yumi Choi (NOIRLab) 
Matthew Hayes (Stockholm University) 
Brandon Hensley (JPL)
Vianney Lebouteiller (Universite' Paris-Saclay) 
Julia Roman-Duval (STScI)

**Comment by AbdallahAE** [comment]
Done!
